### ISSUE TITLE
Google Tag Manager Install on UI (see zombie brain headquarters chat)

### ISSUE THREAD

**Issue by rugzombie** [Rug-Zombie/rug-zombie-uikit#1]
Need to install tag manager (see discord for links etc) 

Will help marketing keep track of progress on marketing goals.

**Comment by CryptoWingnut** [comment]
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id=%27+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-5BV6KHK');</script>

that one is in head
this one is in body

<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-5BV6KHK"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
