### ISSUE TITLE
Create ZombieSwap page

### ISSUE THREAD

**Issue by nnamss** [Rug-Zombie/rug-zombie-uikit#8]
We want to create a swap interface similar to pancakeswap, except it's going to interact with autoshark's [FINS Router](https://bscscan.com/address/0xb0eeb0632bab15f120735e5838908378936bd484#code). We can start with setting up the frontend and can pair on the blockchain integration if any guidance is needed.

You can pick up from where @CryptoWingnut left of on the [zombie-swap branch.](https://github.com/Rug-Zombie/rug-zombie-frontend/tree/zombie-swap)

Example swap interface:
- [This](https://github.com/pancakeswap/pancake-frontend/tree/develop/src/views/Swap) is how pancakeswap implemented it on their repo, you can use it as inspiration but can also recreate a simpler version if you'd like.
![Screen Shot 2021-10-24 at 1 17 36 PM](https://user-images.githubusercontent.com/10407499/138605273-92e4c4f7-3e42-40b8-963f-57f55ce56c18.png)

![Screen Shot 2021-10-24 at 1 17 29 PM](https://user-images.githubusercontent.com/10407499/138605275-4e6ec29e-ec75-450b-b381-80ce737bd3e1.png)

**Comment by aubundy** [comment]
@nnamss here's what I have remaining on this.

- update some uikit components
- update to use our theme
- integrate with blockchain

I'll need to pair up on the blockchain integration part. Please let me know when you have time to do that
